server.port=5000
api.key=938a1cb8-10ca-4198-a20e-c3b4f7b5864e
spring.data.mongodb.uri=mongodb+srv://read_write:EfeJULI8xNfrDI8C@production.zxvgvg6.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=session